### ISSUE TITLE
Ensure max file handles (ulimit -n) extended for all cloud providers

### ISSUE THREAD

**Issue by tgruben** [pilosa/infrastructure#21]
Just a reminder to make sure the max file handles is increased to at least 32K, maybe even 64k from the default 1k on ubuntu boxen for all pilosa node instances

**Comment by jaffee** [comment]
make sure ansible pilosa.yml sets open file limit super high and that should knock this out.

**Comment by codysoyland** [comment]
Confirmed this is done in Ansible.
