### ISSUE TITLE
k8 and ks3

### ISSUE THREAD

**Issue by ghost** [pilosa/infrastructure#34]
Any plans to support kubernetes ?

**Comment by jaffee** [comment]
Yes... not sure when though.

Pilosa, I think, has the features we need to do this, so it's a matter of figuring out the k8s stuff with persistent state, etc.

**Comment by codysoyland** [comment]
We have published a Helm chart for Pilosa. Please have a look and file any relevant issues there: https://github.com/pilosa/helm
